# Metadata for code examples in Physical AI & Humanoid Robotics Textbook
# Each example should be tagged with appropriate categories and requirements

module-1:
  examples:
    - id: example-1-sensor-loop
      title: "Conceptual Sensor Loop"
      description: "Basic sensor loop implementation for humanoid robots"
      file: "code/module-1/example-1-sensor-loop.py"
      tags: ["sensors", "loop", "conceptual"]
      gpu_required: false
      complexity: beginner
    - id: example-2-balance-logic
      title: "Balance Logic"
      description: "Conceptual balance logic for humanoid stability"
      file: "code/module-1/example-2-balance-logic.py"
      tags: ["balance", "stability", "conceptual"]
      gpu_required: false
      complexity: beginner
    - id: example-3-object-recognition
      title: "Object Recognition"
      description: "Conceptual object recognition implementation"
      file: "code/module-1/example-3-object-recognition.py"
      tags: ["perception", "recognition", "conceptual"]
      gpu_required: false
      complexity: intermediate
    - id: example-4-digital-twin
      title: "Digital Twin"
      description: "Conceptual digital twin implementation"
      file: "code/module-1/example-4-digital-twin.py"
      tags: ["digital-twin", "simulation", "conceptual"]
      gpu_required: false
      complexity: intermediate
    - id: example-5-embodiment
      title: "Embodiment"
      description: "Conceptual embodiment principles implementation"
      file: "code/module-1/example-5-embodiment.py"
      tags: ["embodiment", "ai", "conceptual"]
      gpu_required: false
      complexity: intermediate

module-2:
  examples:
    - id: example-1-physics-scenario
      title: "Physics Scenario"
      description: "Pseudo physics scenario for humanoid interaction"
      file: "code/module-2/example-1-physics-scenario.py"
      tags: ["physics", "simulation", "conceptual"]
      gpu_required: false
      complexity: intermediate
    - id: example-2-human-robot-interaction
      title: "Human-Robot Interaction"
      description: "Conceptual human-robot interaction implementation"
      file: "code/module-2/example-2-human-robot-interaction.py"
      tags: ["interaction", "dialogue", "conceptual"]
      gpu_required: false
      complexity: intermediate
    - id: example-3-contact-modeling
      title: "Contact Modeling"
      description: "Conceptual contact modeling for physical interaction"
      file: "code/module-2/example-3-contact-modeling.py"
      tags: ["contact", "physics", "modeling"]
      gpu_required: false
      complexity: advanced
    - id: example-4-force-analysis
      title: "Force Analysis"
      description: "Conceptual force analysis for humanoid movement"
      file: "code/module-2/example-4-force-analysis.py"
      tags: ["force", "analysis", "physics"]
      gpu_required: false
      complexity: advanced
    - id: example-5-friction-modeling
      title: "Friction Modeling"
      description: "Conceptual friction modeling for ground interaction"
      file: "code/module-2/example-5-friction-modeling.py"
      tags: ["friction", "physics", "modeling"]
      gpu_required: false
      complexity: advanced

module-3:
  examples:
    - id: example-1-vision-pipeline
      title: "Vision Pipeline"
      description: "Conceptual vision pipeline implementation"
      file: "code/module-3/example-1-vision-pipeline.py"
      tags: ["vision", "pipeline", "perception"]
      gpu_required: false
      complexity: intermediate
    - id: example-2-frame-analysis
      title: "Frame Analysis"
      description: "Conceptual frame analysis for visual processing"
      file: "code/module-3/example-2-frame-analysis.py"
      tags: ["vision", "analysis", "frames"]
      gpu_required: false
      complexity: intermediate
    - id: example-3-slam-concept
      title: "SLAM Concept"
      description: "Conceptual SLAM implementation"
      file: "code/module-3/example-3-slam-concept.py"
      tags: ["slam", "mapping", "navigation"]
      gpu_required: false
      complexity: advanced
    - id: example-4-map-types
      title: "Map Types"
      description: "Conceptual implementation of different map types"
      file: "code/module-3/example-4-map-types.py"
      tags: ["mapping", "grid", "topological"]
      gpu_required: false
      complexity: intermediate
    - id: example-5-pseudo-mapping
      title: "Pseudo Mapping"
      description: "Conceptual pseudo mapping implementation"
      file: "code/module-3/example-5-pseudo-mapping.py"
      tags: ["mapping", "conceptual", "simulation"]
      gpu_required: false
      complexity: intermediate

module-4:
  examples:
    - id: example-1-kinematics
      title: "Kinematics"
      description: "Conceptual kinematics implementation"
      file: "code/module-4/example-1-kinematics.py"
      tags: ["kinematics", "motion", "math"]
      gpu_required: false
      complexity: intermediate
    - id: example-2-arm-reach
      title: "Arm Reach"
      description: "Conceptual arm reach logic implementation"
      file: "code/module-4/example-2-arm-reach.py"
      tags: ["kinematics", "arm", "motion"]
      gpu_required: false
      complexity: intermediate
    - id: example-3-decision-tree
      title: "Decision Tree"
      description: "Decision tree for humanoid behavior"
      file: "code/module-4/example-3-decision-tree.py"
      tags: ["decision", "logic", "behavior"]
      gpu_required: false
      complexity: intermediate
    - id: example-4-rule-based
      title: "Rule-Based Decisions"
      description: "Rule-based decision system for humanoid"
      file: "code/module-4/example-4-rule-based.py"
      tags: ["decision", "rules", "behavior"]
      gpu_required: false
      complexity: intermediate
    - id: example-5-system-overview
      title: "System Overview"
      description: "Complete system overview implementation"
      file: "code/module-4/example-5-system-overview.py"
      tags: ["system", "integration", "overview"]
      gpu_required: false
      complexity: advanced
