# Metadata for diagrams in the Physical AI & Humanoid Robotics Textbook
diagrams:
  # Module 1 diagrams
  - id: "module-1-diagram-1"
    title: "Sensor → Brain → Action Flow"
    altText: "Diagram showing the flow from sensor input through brain processing to action output in a robotic system"
    caption: "The fundamental flow of information in a robotic system: sensors capture environmental data, the brain processes this information, and actions are executed based on the processed data."
    module: "module-1"
    filePath: "diagrams/module-1/diagram-1-sensor-flow.svg"
    accessibilityCompliant: true
  - id: "module-1-diagram-2"
    title: "Perception Stages"
    altText: "Diagram illustrating the different stages of perception in robotics: sensing, processing, interpretation, and understanding"
    caption: "The stages of perception in robotic systems, showing how raw sensor data is transformed into meaningful environmental understanding."
    module: "module-1"
    filePath: "diagrams/module-1/diagram-2-perception-stages.svg"
    accessibilityCompliant: true
  - id: "module-1-diagram-3"
    title: "Real World ↔ Digital World Loop"
    altText: "Diagram showing the bidirectional relationship between the real physical world and its digital representation in a digital twin system"
    caption: "The continuous loop between the real physical world and its digital representation, where real-world data updates the digital model and digital insights guide real-world actions."
    module: "module-1"
    filePath: "diagrams/module-1/diagram-3-real-digital-loop.svg"
    accessibilityCompliant: true

  # Module 2 diagrams
  - id: "module-2-diagram-1"
    title: "Physics Sketch"
    altText: "Simple diagram showing physical concepts relevant to humanoid robotics: contact points, friction forces, and ground interaction"
    caption: "Basic physics concepts in humanoid robotics, illustrating how robots interact with the physical world through contact points and force application."
    module: "module-2"
    filePath: "diagrams/module-2/diagram-1-physics-sketch.svg"
    accessibilityCompliant: true
  - id: "module-2-diagram-2"
    title: "Human-Robot Loop"
    altText: "Diagram showing the interaction loop between humans and robots: human action, robot perception, robot response, human perception"
    caption: "The bidirectional interaction loop in human-robot interaction, showing how humans and robots perceive and respond to each other's actions."
    module: "module-2"
    filePath: "diagrams/module-2/diagram-2-human-robot-loop.svg"
    accessibilityCompliant: true

  # Module 3 diagrams
  - id: "module-3-diagram-1"
    title: "Vision Pipeline"
    altText: "Diagram showing the stages of a computer vision pipeline: image capture, preprocessing, feature extraction, analysis, and interpretation"
    caption: "The stages of a computer vision pipeline in robotics, showing how visual information is processed from raw images to meaningful understanding."
    module: "module-3"
    filePath: "diagrams/module-3/diagram-1-vision-pipeline.svg"
    accessibilityCompliant: true
  - id: "module-3-diagram-2"
    title: "Mapping Loop"
    altText: "Diagram showing the mapping process: sensor data, map building, localization, path planning, and navigation"
    caption: "The mapping and localization loop in robotics, showing how robots build maps of their environment and use them for navigation."
    module: "module-3"
    filePath: "diagrams/module-3/diagram-2-mapping-loop.svg"
    accessibilityCompliant: true
  - id: "module-3-diagram-3"
    title: "Navigation Flowchart"
    altText: "Flowchart showing the decision process for robot navigation: goal, path planning, obstacle detection, path adjustment, and movement"
    caption: "The decision flow for robot navigation, showing how robots plan paths, detect obstacles, and adjust their movement accordingly."
    module: "module-3"
    filePath: "diagrams/module-3/diagram-3-navigation-flowchart.svg"
    accessibilityCompliant: true

  # Module 4 diagrams
  - id: "module-4-diagram-1"
    title: "Limb Sketch"
    altText: "Simple diagram showing the kinematic structure of a robotic limb: joints, links, and degrees of freedom"
    caption: "The kinematic structure of a robotic limb, showing joints, links, and degrees of freedom that enable movement and manipulation."
    module: "module-4"
    filePath: "diagrams/module-4/diagram-1-limb-sketch.svg"
    accessibilityCompliant: true
  - id: "module-4-diagram-2"
    title: "Decision Logic"
    altText: "Diagram showing a decision tree or logic flow for robot decision-making: inputs, processing nodes, and action outputs"
    caption: "The decision-making logic in robots, showing how inputs are processed through logical structures to produce appropriate actions."
    module: "module-4"
    filePath: "diagrams/module-4/diagram-2-decision-logic.svg"
    accessibilityCompliant: true
  - id: "module-4-diagram-3"
    title: "End-to-End Humanoid Loop"
    altText: "Diagram showing the complete humanoid system: sensors, perception, thinking, action, and the continuous loop"
    caption: "The complete humanoid system loop, showing how sensors, perception, thinking, and action work together in a continuous cycle."
    module: "module-4"
    filePath: "diagrams/module-4/diagram-3-end-to-end-loop.svg"
    accessibilityCompliant: true
