# Metadata for diagrams in Physical AI & Humanoid Robotics Textbook
# Each diagram should be tagged with appropriate categories and accessibility compliance

module-1:
  diagrams:
    - id: diagram-1-sensor-flow
      title: "Sensor → Brain → Action Flow"
      file: "diagrams/module-1/diagram-1-sensor-flow.svg"
      alt_text: "Flowchart showing sensor data flowing to brain processing and resulting in action"
      caption: "Conceptual flow of sensor data processing in humanoid robots"
      tags: ["sensors", "flow", "processing"]
      accessibility_compliant: true
    - id: diagram-2-perception-stages
      title: "Perception Stages"
      file: "diagrams/module-1/diagram-2-perception-stages.svg"
      alt_text: "Diagram showing stages of perception processing from raw sensor data to high-level understanding"
      caption: "Stages of perception processing in humanoid robots"
      tags: ["perception", "stages", "processing"]
      accessibility_compliant: true
    - id: diagram-3-real-digital-loop
      title: "Real World ↔ Digital World Loop"
      file: "diagrams/module-1/diagram-3-real-digital-loop.svg"
      alt_text: "Bidirectional loop showing interaction between real world physical systems and digital world representation"
      caption: "The loop between physical reality and digital representation in humanoid robotics"
      tags: ["digital-twin", "loop", "embodiment"]
      accessibility_compliant: true

module-2:
  diagrams:
    - id: diagram-1-physics-sketch
      title: "Physics Sketch"
      file: "diagrams/module-2/diagram-1-physics-sketch.svg"
      alt_text: "Simple sketch showing physics concepts relevant to humanoid robots"
      caption: "Basic physics concepts for humanoid robot interaction with environment"
      tags: ["physics", "contact", "forces"]
      accessibility_compliant: true
    - id: diagram-2-human-robot-loop
      title: "Human-Robot Interaction Loop"
      file: "diagrams/module-2/diagram-2-human-robot-loop.svg"
      alt_text: "Loop diagram showing bidirectional interaction between human and robot"
      caption: "The interaction loop between humans and humanoid robots"
      tags: ["interaction", "dialogue", "loop"]
      accessibility_compliant: true

module-3:
  diagrams:
    - id: diagram-1-vision-pipeline
      title: "Vision Pipeline"
      file: "diagrams/module-3/diagram-1-vision-pipeline.svg"
      alt_text: "Pipeline diagram showing stages of visual processing from image capture to interpretation"
      caption: "The vision processing pipeline in humanoid robots"
      tags: ["vision", "pipeline", "processing"]
      accessibility_compliant: true
    - id: diagram-2-mapping-loop
      title: "Mapping Loop"
      file: "diagrams/module-3/diagram-2-mapping-loop.svg"
      alt_text: "Loop diagram showing the process of creating and updating environmental maps"
      caption: "The mapping process in humanoid robots"
      tags: ["mapping", "slam", "environment"]
      accessibility_compliant: true
    - id: diagram-3-navigation-flowchart
      title: "Navigation Flowchart"
      file: "diagrams/module-3/diagram-3-navigation-flowchart.svg"
      alt_text: "Flowchart showing decision points in robot navigation process"
      caption: "Navigation decision flow in humanoid robots"
      tags: ["navigation", "planning", "flowchart"]
      accessibility_compliant: true

module-4:
  diagrams:
    - id: diagram-1-limb-sketch
      title: "Simple Limb Sketch"
      file: "diagrams/module-4/diagram-1-limb-sketch.svg"
      alt_text: "Simple sketch of a humanoid limb showing joints and degrees of freedom"
      caption: "Basic structure of a humanoid limb"
      tags: ["kinematics", "limb", "structure"]
      accessibility_compliant: true
    - id: diagram-2-decision-logic
      title: "Decision Logic"
      file: "diagrams/module-4/diagram-2-decision-logic.svg"
      alt_text: "Diagram showing decision logic flow in humanoid behavior"
      caption: "Decision logic structure in humanoid robots"
      tags: ["decision", "logic", "behavior"]
      accessibility_compliant: true
    - id: diagram-3-end-to-end-loop
      title: "End-to-End Humanoid Loop"
      file: "diagrams/module-4/diagram-3-end-to-end-loop.svg"
      alt_text: "Complete system diagram showing the full humanoid control loop"
      caption: "The complete humanoid control loop from sensing to action"
      tags: ["system", "integration", "loop"]
      accessibility_compliant: true
